[project]
name = "iot_comm"
version = "1.0.0"
description = "tcp communication tets program"
dependencies = [
	"notebook",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"